export const CREATE_SAILOR_REQUESTED = "sailors/CREATE_SAILOR_REQUESTED";
export const CREATE_SAILOR_SUCCEEDED = "sailors/CREATE_SAILOR_SUCCEEDED";
export const CREATE_SAILOR_FAILED = "sailors/CREATE_SAILOR_FAILED";

export const FETCH_SAILORS_REQUESTED = "sailors/FETCH_SAILORS_REQUESTED";
export const FETCH_SAILORS_SUCCEEDED = "sailors/FETCH_SAILORS_SUCCEEDED";
export const FETCH_SAILORS_FAILED = "sailors/FETCH_SAILORS_FAILED";

export const UPDATE_SAILOR_REQUESTED = "sailors/UPDATE_SAILOR_REQUESTED";
export const UPDATE_SAILOR_SUCCEEDED = "sailors/UPDATE_SAILOR_SUCCEEDED";
export const UPDATE_SAILOR_FAILED = "sailors/UPDATE_SAILOR_FAILED";

export const DELETE_SAILOR_REQUESTED = "sailors/DELETE_SAILOR_REQUESTED";
export const DELETE_SAILOR_SUCCEEDED = "sailors/DELETE_SAILOR_SUCCEEDED";
export const DELETE_SAILOR_FAILED = "sailors/DELETE_SAILOR_FAILED";

export const SET_SELECTED_SAILOR = "sailors/SET_SELECTED_SAILOR";
